filepath_path_gt = '../input/gt'
filepath_video_games = '../input/video_games.txt'
csv_doc_dict = '../output/processed_docs.csv.gz'
tfidf_matrix_csv_path = '../output/tfidf_matrix.npz'
inverted_index_folder = '../output/spimi_output'
